name: mapiqo

services:
  frontend:
    depends_on:
      backend:
        condition: service_healthy
    container_name: mapiqo-frontend
    env_file:
      - ./mapiqo-frontend/.env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    ports:
      - "3004:3000"
  backend:
    depends_on:
      database:
        condition: service_healthy
    container_name: mapiqo-backend
    env_file:
      - ./mapiqo-backend/.env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    ports:
      - 5004:5000

  database:
    container_name: mapiqo-database
    env_file:
      - ./mapiqo-database/.env.production
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:15
    restart: on-failure
    ports:
      - 5437:5432

volumes:
  db-data:
    name: mapiqo-db-data
